version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel
      POSTGRES_DB: sentinel_db
    # Expose to host only if you need local access; remove ports in production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel -d sentinel_db"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://sentinel:sentinel@postgres:5432/sentinel_db
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    # For local development you can mount the source. Remove the volume for production images.
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"

  web:
    build:
      context: ./front-end/vite-project
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "5173:5173"
    environment:
      # When running in the same compose network, use the service name 'api'
      VITE_API_BASE_URL: http://api:4000
    volumes:
      - ./front-end/vite-project:/app
    command: sh -c "npm install && npm run dev"

volumes:
  postgres_data:
