global:
  scrape_interval: 15s # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules
  external_labels:
    monitor: "sentinel-monitor"

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape the Sentinel API service
  - job_name: "sentinel-api"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:4000"]
        labels:
          service: "sentinel-api"
          environment: "development"

  # Scrape PostgreSQL metrics (if you add postgres_exporter later)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Scrape Redis metrics (if you add redis_exporter later)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
